### ISSUE TITLE
請問是否可以提供 「縫合楷 CL」 ？

### ISSUE THREAD

**Issue by kanwakyuudai** [lxgw/FusionKai#2]
例如：
縫合楷 CL：舊字型（傳承字型）優先，由「霞鶩文楷 TC」「Klee One」（日文漢字部份）「霞鹜文楷」（簡化字部份）依次合并而成。

**Comment by lxgw** [comment]
建议您直接选用[霞鹜文楷 TC](https://github.com/lxgw/lxgwwenkaitc)。

**Comment by kanwakyuudai** [comment]
感謝回覆，我是將「霞鶩文楷 TC」作爲輸入法顯示字體使用的。與「霞鶩文楷」相比，很多字會回退到默認宋體，使風格不一致，故開此 issue 。

**Comment by kanwakyuudai** [comment]
> 建议您直接选用[霞鹜文楷 TC](https://github.com/lxgw/lxgwwenkaitc)。

感謝回覆，我是將「霞鶩文楷 TC」作爲輸入法顯示字體使用的。與「霞鶩文楷」相比，很多字會回退到默認宋體，使風格不一致，故開此 issue 。

**Comment by lxgw** [comment]
缝合楷的字库大小与文楷 Lite、TC 版本一致。
