### ISSUE TITLE
是否有计划推出「缝合楷 T」的屏幕阅读版？

### ISSUE THREAD

**Issue by Louie997** [lxgw/FusionKai#3]
您好：
请问是否有计划针对「缝合楷 T」推出类似于「霞鹜文楷屏幕阅读版」这种适合 PC 阅读的版本？

非常感谢您分享的字体。

**Comment by lxgw** [comment]
没有这个计划，抱歉。

**Comment by Louie997** [comment]
那「霞鹜文楷 屏幕阅读版」有没有计划推出中文标点符号（例如逗号、句号等等）置于正中的版本？
如果没有，可以请教一下如何修改中文标点符号的位置（需要用什么软件）吗？
想弄一个标点符号置中的版本自用。
